steps:
  # Étape 1 : Vérifier et gérer les changements dans les Cloud Functions
  - name: "gcr.io/cloud-builders/git"
    id: Handle Cloud Function changes
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "🔍 Checking for Cloud Function changes..."
        if git diff --name-only $COMMIT_SHA^..$COMMIT_SHA | grep -q "^cloud_functions/"; then
          echo "✅ Cloud Function changes detected"
          
          # Définir le nom du bucket pour les Cloud Functions
          BUCKET_NAME_FUNCTION="$PROJECT_ID-function-code"
          echo "📤 Uploading Cloud Function code to GCS bucket: $BUCKET_NAME_FUNCTION"
          
          # Upload du dossier contenant le code Cloud Function dans le bucket GCS
          gsutil -m cp -r cloud_functions/* gs://$BUCKET_NAME_FUNCTION/cloud_functions/

          # Déployer la Cloud Function via Terraform
          echo "🚀 Deploying Cloud Function via Terraform target..."
          terraform -chdir=/workspace/terraform init
          terraform -chdir=/workspace/terraform apply -auto-approve -target=google_cloudfunctions_function.simulate_logs
        else
          echo "ℹ️ No Cloud Function changes"
        fi

        

        


  # Étape 2 : Vérifier et gérer les changements dans les DAGs
  - name: "gcr.io/cloud-builders/git"
    id: Handle DAG changes
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "🔍 Checking for DAG changes..."
        if git diff --name-only $COMMIT_SHA^..$COMMIT_SHA | grep -q "^dags/"; then
          echo "✅ DAG changes detected"
          BUCKET_NAME_DAGS="$PROJECT_ID-composer-dags"
          echo "📤 Uploading DAGs to GCS bucket: $BUCKET_NAME_DAGS"
          gsutil -m cp -r dags/ gs://$BUCKET_NAME_DAGS/dags/
        else
          echo "ℹ️ No DAG changes"
        fi

  # Étape 3 : Vérifier et gérer les changements dans Terraform (hors cloud_function.tf)
  - name: "gcr.io/cloud-builders/git"
    id: Handle Terraform changes
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "🔍 Checking for general Terraform changes (excluding cloud_function.tf)..."
        if git diff --name-only $COMMIT_SHA^..$COMMIT_SHA | grep -q "^terraform/" && ! git diff --name-only $COMMIT_SHA^..$COMMIT_SHA | grep -q "terraform/cloud_function.tf"; then
          echo "✅ General Terraform changes detected"
          terraform -chdir=/workspace/terraform init
          terraform -chdir=/workspace/terraform apply -auto-approve
        else
          echo "ℹ️ No general Terraform changes (or only cloud_function.tf modified)"
        fi


